### ISSUE TITLE
HP ammo does infinite damage

### ISSUE THREAD

**Issue by buckash105** [CurlySparkle/ARC9-GSR#12]
Hollow point ammunition seems to do an infinite amount of damage. I have uninstalled every other addon I have to ensure it isn't some weird damage multiplier thing from another addon, yet the issue seems to persist. You can one-shot Hunters, Hunter-Choppers, and Striders with it. I have also been instakilled by NPCs using hollow points.

https://user-images.githubusercontent.com/122404048/211661409-6daec618-90cf-44f8-b6dd-4d35b97f7850.mp4

**Comment by TheOnly8Z** [comment]
ARC9 issue. I'll make an issue on the main page
