### ISSUE TITLE
Taller than average or shoter playermodels

### ISSUE THREAD

**Issue by BOTxMALWARY** [CurlySparkle/ARC9-GSR#17]
Taller than average or shoter playermodels cause this stretching visual bug, I just hope there'll be some pm height adjustment for anims. Also there's some thumb bone problem with this pm only, but other swep mods work at their finest, mostly not the arc9 addon issue but anyway
![image](https://user-images.githubusercontent.com/122258726/211919848-2b665281-8618-48e4-bdc9-7dfee74be004.png)

**Comment by Seulyy** [comment]
yes this is mostly the base's fault due to how tpik works ends up ruining proportioned characters.
