### ISSUE TITLE
M203 sight Lua error

### ISSUE THREAD

**Issue by Sninctbur** [CurlySparkle/ARC9-GSR#2]
This error occurs when attempting to switch to the M203 sights in ADS. This doesn't occur with no extra sights attached. (This might be a base issue.)

[ARC9 Weapon Base] lua/weapons/arc9_base/sh_sights.lua:294: attempt to index a nil value
  1. SwitchMultiSight - lua/weapons/arc9_base/sh_sights.lua:294
   2. ThinkSights - lua/weapons/arc9_base/sh_sights.lua:121
    3. unknown - lua/weapons/arc9_base/sh_think.lua:90

**Comment by Seulyy** [comment]
When did this happen? i can't seem to replicate the issue, what are the steps so i can replicate it?

**Comment by Sninctbur** [comment]
I did this with the AK-47. Add an M203 and the sights, enter ADS, and try to switch sights with Alt-E.

**Comment by Seulyy** [comment]
https://user-images.githubusercontent.com/5094277/210194269-138d7cd9-0ab1-4d05-925f-14fede48df0c.mp4

Sadly i can't seem to replicate the issue

**Comment by Sninctbur** [comment]
Don't switch to the UBGL. Use the gun's sights.

**Comment by Seulyy** [comment]
I just did recently and so far still no error about it, can you try to see if you can record it and see if you get the error?

**Comment by Sninctbur** [comment]
https://user-images.githubusercontent.com/29333347/210288549-93067960-a37b-4e44-b5ca-34c75c7fb448.mp4

Recorded with current Workshop versions of both the base and the pack.

**Comment by Seulyy** [comment]
Just did it like this now and yeah, its a confirmed bug related on the main base, gonna closed this and thanks for the report, hopefully this gets fixed. 👍🏻
