### ISSUE TITLE
TPIK question

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-GSR#22]
The third person weapon does not hang up when the round is finished, but you can see the weapon hang up in the first person, only when the round is finished ,press reload then you can see the third person weapon hang up few sconds
![20230112141740_1](https://user-images.githubusercontent.com/116985165/211992267-e55538bc-714e-4c63-bbdb-b0d11a647508.jpg)
![20230112141749_1](https://user-images.githubusercontent.com/116985165/211992276-16ef8fe5-d095-4524-9099-cc11c7d11e87.jpg)

**Comment by mwxmwh** [comment]
Not only this mod has this problem, your other mods have this problem as well

**Comment by Seulyy** [comment]
base issue
