### ISSUE TITLE
C4 Explosion Error Message

### ISSUE THREAD

**Issue by ghost** [CurlySparkle/ARC9-GSR#27]
Hello, I'm having a small problem when using the "C4 Explosive". Everything else is fine, however when I try to detonate the C4, I get this message, any feedback/fixing would be appreciated, thank you and keep up the good work! :))

[ARC9 Weapon Base] lua/weapons/arc9_base/sh_grenade.lua:160: attempt to call method 'Detonate' (a nil value)
  1. TouchOff - lua/weapons/arc9_base/sh_grenade.lua:160
   2. swepThinkGrenade - lua/weapons/arc9_base/sh_grenade.lua:6
    3. unknown - lua/weapons/arc9_base/sh_think.lua:159
    
![expo](https://user-images.githubusercontent.com/123845003/215296597-0a7448ea-b6bb-48aa-8c3e-d881a2553f14.PNG)

   
![error](https://user-images.githubusercontent.com/123845003/215296562-5d5bac4e-ddee-483d-a80f-5f9873f42e22.PNG)

**Comment by TheOnly8Z** [comment]
Base issue, should be fixed now.
