### ISSUE TITLE
MAC-10 shouldn't be able to chamber an extra round

### ISSUE THREAD

**Issue by Samarai** [CurlySparkle/ARC9-GSR#31]
I know gun pedantry like this is the most obnoxious shit ever, but still; the MAC-10 holds an extra round if reloaded while not completely empty, but due to realistically being an open bolt weapon it can't do that. (Funnily enough, the inspect animation for it even shows this- you can peek inside the action.)

Additionally, the trivia section lists its caliber as 5.56 NATO, but I'm assuming that'll be touched up with the recent wave of commits relating to weapon trivia.

**Comment by MokaAkashiya85** [comment]
Fixed.
