### ISSUE TITLE
Black Screen on Map Load

### ISSUE THREAD

**Issue by new01** [CurlySparkle/ARC9-GSR#32]
Maps that break when using this mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2722052799

When loading any map other than the first one (shoot_bang1) included in this pack the screen stays black. I've narrowed it down to just this addon that is causing this issue. 

**How to reproduce this issue:**
1.  Subscribe and enable to the Shoot Bang Campaign Map Pack (https://steamcommunity.com/sharedfiles/filedetails/?id=2722052799)
2.  Subscribe and enable to the latest version of ARC9 Weapon Base, and ARC9-GSR.
3.  Load map shootbang_2
4.  Map will now display a black screen, intro text will still display above map.

**Comment by new01** [comment]
Note that I disabled every single addon except for the three I listed above to narrow down the issue.

**Comment by Seulyy** [comment]
base issue
