### ISSUE TITLE
Subatts do not work in multiplayer

### ISSUE THREAD

**Issue by OddInc** [CurlySparkle/ARC9-GSR#37]
Most likely caused by the following error:

[[ARC9] Gunsmith Reloaded] lua/arc9/common/attachments/csgo_rail_optic_1.lua:20: attempt to call method 'GetPhrase' (a nil value)
  1. unknown - lua/arc9/common/attachments/csgo_rail_optic_1.lua:20
   2. include - [C]:-1
    3. LoadAtts - lua/arc9/shared/sh_atts.lua:109
     4. unknown - lua/arc9/shared/sh_atts.lua:270
      5. include - [C]:-1
       6. unknown - lua/autorun/sh_arc9_autorun.lua:15

This error is present for every att that support subatts.
Using the WS build of everything.

**Comment by MokaAkashiya85** [comment]
Noted.

To temporarily fix it for your server, open the ARC9 options menu, go to Developer and click "Reload Attachments" - that'll fix the issue for that session.

**Comment by MokaAkashiya85** [comment]
This should be temporarily fixed on the Workshop release while hopefully being fixed permanently later on.
