### ISSUE TITLE
15-Round .338 AWM magazine for the AWP lists no trade-off.

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-GSR#49]
The 15-Round .338 AWM magazine for the AWP states that the reload speed is slower when attached, but appears and functions as a straight upgrade. The reload speed is the same as the standard 10-round magazine. 
![20230824191712_1](https://github.com/CurlySparkle/ARC9-GSR/assets/41251184/35013613-8804-4d84-aafc-5f6a90a48399)

**Comment by Seulyy** [comment]
should be fixed on next update
