### ISSUE TITLE
Almost every gun position is offset

### ISSUE THREAD

**Issue by BOTxMALWARY** [CurlySparkle/ARC9-GSR#5]
![image](https://user-images.githubusercontent.com/122258726/211260835-dd11826b-47b5-4040-b107-be5cd672900e.png)
(Attention to the tracer)
In thirdperson bullet comes out in one angle, but weapon looking into another, making it kinda goofy

**Comment by Seulyy** [comment]
not sure if something can be done about that but will be talked about it with other people.
