### ISSUE TITLE
MP5-SD making only first three shots sounds

### ISSUE THREAD

**Issue by BOTxMALWARY** [CurlySparkle/ARC9-GSR#6]
It just makes three shots in thirdperson, but then you can hear shots only in first person, is it intended? Idk

**Comment by BOTxMALWARY** [comment]
> It just makes three shots in thirdperson, but then you can hear shots only in first person, is it intended? Idk

Le demonstration

https://user-images.githubusercontent.com/122258726/211329076-de5315cf-c15d-4655-93a6-ec3dfea7adae.mp4

**Comment by CturiX** [comment]
Noticed the other day, the original sound length is far too long and has an identical sound playing, hense why its loud only sometimes or is completely silent
Will be addressing it shortly with new audio.

**Comment by BOTxMALWARY** [comment]
> Noticed the other day, the original sound length is far too long and has an identical sound playing, hense why its loud only sometimes or is completely silent Will be addressing it shortly with new audio.

Cool, I wish you all guys to rig this addon so tight that those third person anims and other things can get to nextgen level, and also I wish you luck
