### ISSUE TITLE
Really weird thirdperson animation bug happens with underbarrel shotgun

### ISSUE THREAD

**Issue by BOTxMALWARY** [CurlySparkle/ARC9-GSR#8]
![image](https://user-images.githubusercontent.com/122258726/211299928-37d87024-d3ec-46d1-b673-41c7a8e22506.png)

**Comment by BOTxMALWARY** [comment]
> ![image](https://user-images.githubusercontent.com/122258726/211299928-37d87024-d3ec-46d1-b673-41c7a8e22506.png)

It happens only when standing idle with underbarrel toggled

**Comment by Seulyy** [comment]
sadly this seems more like a base issue as far as i been told
